### ISSUE TITLE
Error message upon trying to install Rdimtools package

### ISSUE THREAD

**Issue by whytemarine** [kyoustat/Rdimtools#15]
Hi, I have been having trouble installing the Rdimtools package. These error messages have been displayed after each step. Is there a simple solution that I am overlooking? 

1,
devtools::install_github("kisungyou/Rdimtools")

ERROR: package installation failed
Error: Failed to install 'Rdimtools' from GitHub:
  System command 'R' failed, exit status: 1, stdout & stderr were printed
In addition: Warning messages:
1: In i.p(...) : installation of package ‘Rmpfr’ had non-zero exit status
2: In i.p(...) : installation of package ‘CVXR’ had non-zero exit status

2,
install.packages("Rmpfr")

configure: error: Header file mpfr.h not found; maybe use --with-mpfr-include=INCLUDE_PATH
ERROR: configuration failed for package ‘Rmpfr’
* removing ‘/home/people/krw19kxd/R/x86_64-pc-linux-gnu-library/4.1/Rmpfr’
Warning in install.packages :
  installation of package ‘Rmpfr’ had non-zero exit status

3,
install.packages("CVXR")

Warning in install.packages :
  installation of package ‘Rmpfr’ had non-zero exit status
ERROR: dependency ‘Rmpfr’ is not available for package ‘CVXR’
* removing ‘/home/people/krw19kxd/R/x86_64-pc-linux-gnu-library/4.1/CVXR’
Warning in install.packages :
  installation of package ‘CVXR’ had non-zero exit status

4,
install.packages("mpfr.h")

install.packages("mpfr.h")
Installing package into ‘/home/people/krw19kxd/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘mpfr.h’ is not available for this version of R

**Comment by kisungyou** [comment]
Thanks @whytemarine for your interest in the package. For the `Rmpfr`, you need to install GNU Multiple Precision arithmetic library. I recommend you consult this [README](https://cran.r-project.org/web/packages/Rmpfr/readme/README.html) file for `Rmpfr` package. Once done, there should be no problem installing the package.
