### ISSUE TITLE
polynomial kernel, d=2, c=1

### ISSUE THREAD

**Issue by yamauchilab** [kyoustat/Rdimtools#17]
# polynomial kernel of Rdimtools and kernlab return different values. Isn't this a bug?

e.g.,
>     (x = matrix(c(1:6), 2, 3))
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
>     library(Rdimtools)
>     (x_kpoly_Rdim_d2 = aux.kernelcov(x, ktype = c("polynomial", d=2, c=1)))
$K
     [,1] [,2]
[1,]   37   46
[2,]   46   58

$Kcenter
      [,1]  [,2]
[1,]  0.75 -0.75
[2,] -0.75  0.75

>     library(kernlab)
>     linear_kern <- polydot(degree = 2, scale = 1, offset=1)
>     (x_kpoly_d2_kernlab = kernelMatrix(kernel = linear_kern, x=x))
An object of class "kernelMatrix"
     [,1] [,2]
[1,] 1296 2025
[2,] 2025 3249

**Comment by kisungyou** [comment]
@yamauchilab thanks for your input. The `aux.kernelcov` takes a parameter in `ktype` in order, not by assigning in a vector. Hence, in this case, you should use `ktype=c("polynomial",1,2)` in an order of the parameters as described.

**Comment by yamauchilab** [comment]
Oh, I am so sorry. That was my careless mistake.  Takashi
