### ISSUE TITLE
Default npoints for do.lisomap

### ISSUE THREAD

**Issue by ugroempi** [kyoustat/Rdimtools#2]
Thank you for providing Rdimtools!
The default `npoints` for `do.lisomap` causes trouble, if the number of rows is not a multiple of 5. It would be good to include rounding, so that the default is always an integer, e.g. `max(round(nrow(X)/5), ndim +
  1)`

Best, Ulrike

**Comment by kisungyou** [comment]
Hi @ugroempi ,

For LMDS and LISOMAP, they are well represented. Instead of controlling the input option, I took another step to set it during preprocess type. For the versions upcoming, it will have no problem as of your opinion.

Thanks, Kisung
