### ISSUE TITLE
Wish: preprocess type "scale"

### ISSUE THREAD

**Issue by ugroempi** [kyoustat/Rdimtools#3]
Currently, Rdimtools offers centering, decorrelating and whitening, and there is no built-in way to scale the data to a common variance (1) without decorrelating them. This is what I would often like to do, therefore a `type="scale"` possibility would be very much appreciated!

Best, Ulrike

**Comment by kisungyou** [comment]
Hi @ugroempi 

Others have shown similar concerns with respect to the preprocessing option. Other than 3 default options, in the forthcoming update, I'll include "scale" and "cscale" for centering+scaling. Thanks for your note and attention.

Regards
Kisung
