### ISSUE TITLE
Memory issue with do.lmds

### ISSUE THREAD

**Issue by leojoubert** [kyoustat/Rdimtools#4]
Hi,

Thank for you very interresting package. Using it, I encoutered a memory issue executing this code : 

```
library(magrittr)
library(dplyr)
library(Rdimtools)

n <- 1000000

test <- data.frame(cle = c(paste0("N", runif(n, 1, 400) %>% round(0))),
                   deb = runif(n, 1, 5) %>% round(0),
                   fin = runif(n, 6, 12) %>% round(0),
                   stringsAsFactors = F)

test2 <- do.lmds(test[, c("deb", "fin")], npoints=round(nrow(test[, c("deb", "fin")])/100))

```

**Comment by kisungyou** [comment]
Dear @leojoubert ,

Though as you know landmark methods are known to be suitable for large-scale data, in fact, this requires actual loading of the data onto the memory. MDS methods requires (n-by-n) pairwise distance matrix to be loaded in that it does not work on my machine as well. We are planning to make a devoted version of our package using 'bigmemory'-type computing framework but not sure when it would become plausible. 

Regards,
Kisung
