### ISSUE TITLE
do.iltsa() returns weird outlier values

### ISSUE THREAD

**Issue by Kusara** [kyoustat/Rdimtools#7]
This is an excellent library that has helped me a ton, thank you for writing it! 

I'm having an issue with `do.iltsa()` that I've spent a couple of days on and haven't been able to figure out. It keeps returning extreme outlier values after reduction even when the input data is just a swiss roll.

Here's a reproducible example:
```
library(Rdimtools)
library(ggplot2)

swissroll <- aux.gensamples(
  n = 500,
  dname = "swiss"
) 

swiss.iltsa <- do.iltsa(
  swissroll,
  ndim = 2
)

swiss.iltsa.toplot <- as.data.frame(swiss.iltsa$Y)

ggplot(swiss.iltsa.toplot, aes(V1, V2)) + geom_point()
```

Which gives a plot similar to this:
![image](https://user-images.githubusercontent.com/6157495/87906029-b2700b00-ca16-11ea-9138-9c807be5d50b.png)

I'm expecting something much closer to the results in the LTSA paper. Am I doing something wrong? I'm on a fresh install of Rstudio with R version 4.0.2

**Comment by kisungyou** [comment]
Hi @Kusara I'm sorry for the late reply on this issue.
One of the things I learned from developing this package is that a surprisingly large number of algorithms are much sensitive to the choice of hyperparameters. In ILTSA case, we have (1) neighborhood graph construction and (2) heat kernel parameter. For example, the paper assumes 'symmetric' type of graph construction. It means that some sort of 'engineering' might be required for better visualization. So my suggestion is to give a try on a variety of settings for the visualization of your preference.
