### ISSUE TITLE
Can't print full pca

### ISSUE THREAD

**Issue by nspyrison** [kyoustat/Rdimtools#8]
I can't return the last dim of the pca, p-1 seems to work.

``` r
  m <- as.matrix(mtcars)
  Rdimtools::do.pca(m, ndim = ncol(m))
#> Error in dt_pca(X, myndim, myprep, mycor): * do.pca : 'ndim' should be in [1,ncol(X)).
```

<sup>Created on 2021-02-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kisungyou** [comment]
Hi @nspyrison. When you apply PCA with full dimension as of your `ncol(m)`, this is simply whitening. In the spirit of **reducing** dimensionality of the data, I made a common imperative to accept that `ndim` should be smaller than the number of variables.
